package hu.bme.aut.android.myideas.models.network

/**
 * myIdeas
 * This is the openAPI description of myIdeas application.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@myideas.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 * @param id
 * @param title
 * @param description
 * @param shortDescription
 */
data class IdeaNetworkDTO(
    val id: String? = null,
    val title: String? = null,
    val description: String? = null,
    val shortDescription: String? = null
)
